################################# Default configuration ###################
# provide your domain here
baseURL = "https://www.section.io/docs/"
# theme
theme = "dot"
# site title
title = "Section"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#087830"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-home" # themify icon pack : https://themify.me/themify-icons
name = "Section"
link = "https://www.section.io/"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/section-io/docs"
  
[[params.social]]
icon = "ti-comments-smiley" # themify icon pack : https://themify.me/themify-icons
name = "Community"
link = "https://community.section.io/"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2021 Section."

# banner
[Languages.en.params.banner]
title = "Section Documentation"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Please contact a Section engineer by emailing support@section.io."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "How-Tos"
  url = "how-tos"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Tutorials"
  url = "tutorials"
  weight = 2

   [[Languages.en.menu.main]]
  parent = "docs"
  name = "Explanations"
  url = "explanations"
  weight = 3

 [[Languages.en.menu.main]]
  parent = "docs"
  name = "Reference"
  url = "reference"
  weight = 4